### ISSUE TITLE
Integer validation needs regex first

### ISSUE THREAD

**Issue by imsickofmaps** [praekelt/go-rts-zambia#61]
Pile of crap JavaScript is parseInt-ing "10e" into 10 on the validation so passing the state as clean but then saving to the CMS is failing.

**Comment by smn** [comment]
Is this the IMES number?

**Comment by imsickofmaps** [comment]
@smn nope... All the instances of this: https://github.com/praekelt/go-rts-zambia/blob/develop/js_sandbox/lib/go-rts-zambia.js#L654-L657 need this kind of regex first: https://github.com/praekelt/go-rts-zambia/blob/develop/js_sandbox/lib/go-rts-zambia.js#L156-L157

**Comment by smn** [comment]
Ah yes, from [Mozilla](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt):

> If parseInt encounters a character that is not a numeral in the specified radix, it ignores it and all succeeding characters and returns the integer value parsed up to that point. parseInt truncates numbers to integer values. Leading and trailing spaces are allowed.

**Comment by smn** [comment]
But this may be useful:

``` javascript
> Number('10e');
NaN
> Number('10');
10
>
```

**Comment by imsickofmaps** [comment]
Fixed in https://github.com/praekelt/go-rts-zambia/commit/f1e5c58c9e6309a631dfee6784e4ede003cb9c25 and merged into develop by mistake
