### ISSUE TITLE
Registration process ends with error rather than thank you msg

### ISSUE THREAD

**Issue by laurenkotze** [praekelt/go-rts-zambia#66]
In the QA instance of the USSD code (_120_8864*1177#) as well as the live version, either after the question "What is the name and surname of your Zonal Head?" or "Are you a Zonal Head? 1. Yes 2. No", (whichever is the final msg in the registration process), I consistently get an error message rather than "Congratulations! You are now registered as a user of the Gateway! Please dial in again when you are ready to start reporting on teacher and learner performance" or "Well done! You are now registered as a Zonal Head Teacher. When you are ready, dial in to start reporting. You will also receive monthly SMS's from your zone."

Please could you check this out? Thanks.

**Comment by imsickofmaps** [comment]
@laurenkotze I will review this with you Monday.

**Comment by imsickofmaps** [comment]
Fixed in other updates
