### ISSUE TITLE
CMS issues

### ISSUE THREAD

**Issue by laurenkotze** [praekelt/go-rts-zambia#67]
1. In www.zambiaschoolgateway.com (username 'lauren' log-in), under "4. Schools", there is no option under Actions to export a csv of all the schools in the database. Same for all under "Hierarchy". 
2. Under "Data" please remove "Academic Achievement Codes"
3. Please remove the entire section "Djcelery" - this shouldn't be here.

**Comment by imsickofmaps** [comment]
@laurenkotze 2 and 3 are done. Number 1 wasn't ever requested, just downloading of data they entered via the line was in the scope. Do you want that added to the SoW?

**Comment by imsickofmaps** [comment]
Completed 1 in issue #71
