### ISSUE TITLE
SMS via CMS issues

### ISSUE THREAD

**Issue by laurenkotze** [praekelt/go-rts-zambia#74]
1. Cannot export sent sms's or inbound sms's.
2. Cannot delete sent sms's (see screenshot).
3. Read to Succeed user account needs to have all rights possible - at the moment they can't send an SMS, or view received SMSes.
4. How can I send an SMS in production to test that its actually working? I want to send one to Derek Pollard (who I've added as a Head Teacher in the test_zone). I tried to send a msg from my account, and I added myself to the test-district, but then it says the only zones in my district are Temp Sms Zones: #1? Rather than test_zone?

![screen shot 2013-10-29 at 11 37 37 am](https://f.cloud.github.com/assets/5390390/1427111/2f8432a0-4081-11e3-897e-cc4034518fbb.png)

**Comment by imsickofmaps** [comment]
All discussed and dismissed or converted to individual issues here
