### ISSUE TITLE
USSD Change to copy

### ISSUE THREAD

**Issue by laurenkotze** [praekelt/go-rts-zambia#75]
When an EMIS number is not recognized, the following is shown to the head teacher in the USSD flow: "We still don't recognise your EMIS number. Please send a SMS with the words EMIS ERROR to 739 and your DEST will contact you to resolve the problem." NB this number has now changed to 7233 - please could this be updated? Thanks.

**Comment by imsickofmaps** [comment]
@laurenkotze this is a config flag in Vumi Go. I've updated it though and updated the source config file incase it ever gets redeployed to a fresh account.
